language: python
python:
  - "2.7"

install:
  - pip install -e .
  - pip install -r requirements-dev.txt

script:
  - py.test
  - flake8 caenbrew test

deploy:
  provider: pypi
  user: arxanas
  password:
    secure: FqaZKcOqtM7DMinfbt7BMq0inMPlHDpWRSmxnmM+KR22342ojH2O2lzC/ugmVUBVC7RKUmtaaM/+drpYWLEXPj43z7fL0aLqk0Ksz21YqN0mQCfc7wO2U0ylqetRHhLtqAGsSbQlYThe+H+WOZC+Vw11aHWC0yub2Jl/OYbQOZlchpRX572OkHVouOs0RftUFv5luyeLv52M3TNV3UgM3TirQtj+XXxZQ+M07BGbz8j5Bj0O/IOYVR5UZzEaVwqofpY8y5VqysUiE/NwS/uhbWSAZKpodAAU0c+Z+DT6kaMknmM3o+xM46GnrP/VvOGBUCh/FictugP3ZqiL85mD/nMZVKwbMVkjGHhKV48tHz55gVy8ovDUeHcc09Q9v+hrHBE1F77yqECUOKbxuWPE+R0gRu94QJXD2ctXQsKsZytxN6L4sxirBtswSZKtkscy5/gl9tJbVAN6fFzZddTiNZPbwq6ULrLScfTgIt7WEAeYsJcMvVzVqHWasFM40Hf36uDSpKdJjwmwyyRdbNt9vNn1kOMO7IWE4Bg93+Gdbug3UZqeBSUNcPODV3J1Jc06yD0IHGDnKvD3SvbqBMq9fN+XoJQ3ELwOpdRlPSvKwL9N+KJA8znoN46UUaGlk3ugG7T+ml1gm7+KswyGSjYY9BxHfHYGjP4u0+m4fL3uW+Y=
  on:
    tags: true
